### ISSUE TITLE
Feature Request: Add seccompProfile Support to AWX Operator Helm Chart

### ISSUE THREAD

**Issue by siddjellali** [ansible-community/awx-operator-helm#45]
**Description:**

It would be beneficial to include support for specifying a `seccompProfile` in the AWX Operator Helm chart. This enhancement will allow users to implement additional container security measures by enabling seccomp filtering options.

**Motivation:**

Seccomp profiles are an effective means to restrict the system calls available to containers, thereby reducing the potential attack surface. Integrating this feature directly into the Helm chart would improve security for AWX deployments, particularly in production environments where strict security controls are essential.

**Proposed Changes:**

- **New Parameter:**  
  Introduce a new parameter (e.g., `seccompProfile`) in the `values.yaml` file to allow users to specify their desired seccomp profile.

- **Template Update:**  
  Modify the deployment templates to conditionally include the `seccompProfile` setting when provided by the user.

- **Backward Compatibility:**  
  Ensure that the default behavior remains unchanged for users who do not specify a `seccompProfile`.

- **Documentation:**  
  Update the chart's documentation and examples to include guidance on configuring the `seccompProfile`.

**Additional Context:**

Implementing this feature should be a non-breaking change and would provide a valuable security enhancement for users. Feedback on implementation details or alternative approaches is welcome.

Thank you for considering this feature request.

**Comment by siddjellali** [comment]
I would like to add the option in the values.yaml file to include the following configuration in all containers:

```yaml
podSecurityContext:
  fsGroup: 1001

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ "ALL" ]

```
This enhancement would allow for a consistent security configuration across all containers.

**Comment by miles-w-3** [comment]
Good evening @siddjellali, can you elaborate on why the last code block example you provided does not work? It is true that in order to set the security policy for the actual awx web and task, and any ee containers, this would need to be done within the AWX spec. This resource can be configured by the chart as you have done above, or by separate apply. Is it possible you're just missing the `enabled` flag?

```
AWX:
  enabled: true
  spec:
    security_context_settings:
      runAsNonRoot: true
      runAsUser: 1001
      seccompProfile:
        type: RuntimeDefault
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ "ALL" ]
```

The only containers created directly by the operator are those used for the controller - they are not used directly by the awx instance

**Comment by siddjellali** [comment]
Thanks @miles-w-3 
I didn't forget the `enabled` flag, I would have liked...  

![Image](https://github.com/user-attachments/assets/75fe27a5-d6a7-430a-bd92-62f8d157920d)

It seems that the containers **"kube-rbac-proxy"** and **"awx-manager"** do not inherit the **security_context_settings**; this is clearly stated in the logs.

```
Error creating: pods "awx-operator-controller-manager-5ccb88d675-lj795" is forbidden: violates PodSecurity "restricted:latest": seccompProfile (pod or containers "kube-rbac-proxy", "awx-manager" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

**Comment by miles-w-3** [comment]
The clarification is appreciated. Sounds like you are trying to set the security policy for the controller containers, not for the AWX instance itself that is configured by the AWX CRD. As such, this configuration can't be made to the AWX resource. But mergeable configuration of the controller deployment containers will be possible after i implement #47

**Comment by miles-w-3** [comment]
@siddjellali please see #48, specifically [this](https://github.com/ansible-community/awx-operator-helm/pull/48/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R173) example in the README to support container override. It should satisfy your use-case. If you just want to set something at the pod level and not the individual container level, that should be doable right now with the `operator-controller` values field.

**Comment by siddjellali** [comment]
@miles-w-3 any update here ? I'm ready to test it ^^

**Comment by darkhonor** [comment]
I have some additions on this feature request.  I've adjusted the values template to support a more restrictive environment (think DoD STIG). 

```yaml
AWX:
  enabled: true
  # These configurations relate to awx pods created by the operator, *not* the controller pods themselves
  spec:
    admin_user: admin
    service_type: LoadBalancer  
    security_context_settings:
      runAsNonRoot: true
      runAsUser: 1001
      seccompProfile:
        type: RuntimeDefault
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ "ALL" ]
    postgres_security_context_settings:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ "ALL" ]
    postgres_data_volume_init: true
    init_postgres_extra_commands: |
        chown 26:0 /var/lib/pgsql/data
        chmod 700 /var/lib/pgsql/data 

operator-controller-containers:
  # this will get merged into the operator controller deployment spec for
  # the container named `kube-rbac-proxy` at `spec.template.spec.containers`
  kube-rbac-proxy:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
      seccompProfile:
        type: RuntimeDefault
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ "ALL" ]
  # example: override the environment variables of the main controller container
  # note that since `env` is a list, it will be an override instead of a merge
  # so any env var change requires re-specifying the whole list
  awx-manager:
    env:
    - name: ANSIBLE_GATHERING
      value: explicit
    - name: ANSIBLE_DEBUG_LOGS
      value: "true" # default was "false"
    - name: WATCH_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
      seccompProfile:
        type: RuntimeDefault
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ "ALL" ]


operator-controller:
  spec:
    # replicas is an example spec for the deployment
    replicas: 2
    # template drills down into the pod that will be manaeg
    template:
      spec:
        # This is a pod-level override, so it can be applied here
        # and not worry about container list semantics
        securityContext:
          runAsNonRoot: true
          fsGroup: 2000
```

This solved most problems, but now I'm getting an error on the PostgreSQL init container not having it's securityContext set, even though that option is set here.  Unfortunately, I need that init container to prevent a never-ending crash loop backoff error of the database statefulset.

Thoughts?
