### ISSUE TITLE
operator-controller name overrides does not include service naming

### ISSUE THREAD

**Issue by psolomon-services** [ansible-community/awx-operator-helm#50]
For the operator-controller overrides, everything works, including renaming, but this does not carry over to it's service name.  We want all resources created by the helm chart/operator to be prefixed by the `AWX.name` field.

Is there a chance to move the `operator-controller` tag under `AWX` so it can inherit the `AWX.name` field for naming of all created sub-resources (i.e. service name)?  If the Service name could be generated from `operator-controller.metadata.name`, that would suffice as well.

For example, in our config of `AWX.name: awx-poc`, we would want to see naming like this on any generated resource:

```
service/awx-poc-awx-operator-controller-manager-metrics-service
```

In the current helm values file:

```
operator-controller:
  spec:
    replicas: 2
  metadata:
    name:  awx-poc-awx-operator-controller-manager     # matching prefix from AWX.name
    annotations:
      my-key: my-key-value
    labels:
      my-label: my-label-value

AWX:
  enabled: true
  name: awx-poc

  ...
```

After helm deploy, the operator-controller service name gets a default name (no prefix):

```
$ kubectl get pods,deploy,svc -n awx
NAME                                                           READY   STATUS      RESTARTS   AGE
pod/awx-poc-awx-operator-controller-manager-748c67f659-42ttg   2/2     Running     0          14m
pod/awx-poc-awx-operator-controller-manager-748c67f659-tf99q   2/2     Running     0          14m
pod/awx-poc-migration-24.6.1-vq2jb                             0/1     Completed   0          13m
pod/awx-poc-task-b87946986-j4szm                               4/4     Running     0          14m
pod/awx-poc-web-7f4db44cfd-lzxtd                               3/3     Running     0          14m

NAME                                                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/awx-poc-awx-operator-controller-manager   2/2     2            2           14m
deployment.apps/awx-poc-task                              1/1     1            1           14m
deployment.apps/awx-poc-web                               1/1     1            1           14m

NAME                                                      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/awx-operator-controller-manager-metrics-service   ClusterIP   10.96.17.179   <none>        8443/TCP   14m
service/awx-poc-service                                   ClusterIP   10.96.203.65   <none>        80/TCP     14m
```
