### ISSUE TITLE
How to private images

### ISSUE THREAD

**Issue by naveen1583** [ansible-community/awx-operator-helm#56]
Hello,

I will be deploying AWX using the AWX Operator in an air-gapped environment where I do not have internet connectivity. I have pushed all the necessary images to a private repository, but I am unable to determine how to override the image paths in the helm values file.

I would appreciate any suggestions you may have.

**Comment by naveen1583** [comment]
Thank you @miles-w-3  for your response. I managed to override the image source for the operator and awx, except for the init-receptor container. It’s trying to pull the `quay.io/ansible/awx-ee:24.6.1`, even though I specified the `control_plane_ee_image: abc.net/abc/ansible/awx-ee:24.6.1` in values file.

I'm using the latest version as well.
```
apiVersion: v2
appVersion: 2.19.1
description: The community-supported AWX Operator Helm Chart
name: awx-operator
type: application
version: 3.1.0
```

My values file:

```
AWX:
  enabled: true
  name: awx
  spec:
    admin_user: admin
    bundle_cacert_secret: bundle-custom-certs
    ee_images:
      - image: abc.net/ansible/awx-ee:latest
        name: awx-ee
      
      - image: abc.net/kubevirt-awx-ee:latest
        name: kubevirt-awx-ee
    control_plane_ee_image: abc.net/ansible/awx-ee:24.6.1

    image: abc.net/ansible/awx
    image_version: latest

    postgres_image: abc.net/ansible/postgres
    postgres_image_version: latest

    redis_image: abc.net/ansible/redis
    redis_image_version: latest

    image_pull_secret: img-pull-secret
    postgres_resource_requirements: null
    postgres_storage_class: cephfs
    postgres_storage_requirements:
      requests:
        storage: 25Gi
    replicas: 2
    service_type: ClusterIP

operator-controller-containers:
  awx-manager:
    image: abc.net/ansible/awx-operator:latest

  kube-rbac-proxy:
    image: abc.net/ansible/kube-rbac-proxy:latest
    securityContext:
      runAsNonRoot: false
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
serviceAccount:
  imagePullSecrets:
    - name: img-pull-secret

```
